/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-08-13 12:23:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1687867964394L));
    _jspx_dependants.put("jar:file:/C:/Giboo_Take_kh/back/Giboo/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems_005fend_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems_005fend_005fbegin.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!DOCTYPE html>\r\n");
      out.write("        <html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("        <head>\r\n");
      out.write("            <meta charset=\"UTF-8\">\r\n");
      out.write("            <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("            <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("            <title>hunny</title>\r\n");
      out.write("            <!-- jQuery 라이브러리 추가 -->\r\n");
      out.write("            <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"\r\n");
      out.write("                integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main/reset.css\" />\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main/main.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </head>\r\n");
      out.write("        <!-- style=\"overflow-x:hidden; overflow-y:auto;\" -->\r\n");
      out.write("\r\n");
      out.write("        <body style=\"overflow-x: hidden; overflow-y: auto;\">\r\n");
      out.write("            <!-- 헤더 영역 -->\r\n");
      out.write("            <header style=\"z-index: 200;\">\r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/main/header.jsp", out, false);
      out.write("\r\n");
      out.write("            </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("                    <section class=\"welcome\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"main_swiper\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mainImg_wrapper\">\r\n");
      out.write("                                ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mainImg_slide active\">\r\n");
      out.write("                                <h1 class=\"sec1_h1_style\">\r\n");
      out.write("                                    바쁜 현대 사회에서 <br> 혼자라는 느낌이 들 때,\r\n");
      out.write("                                </h1>\r\n");
      out.write("                                <p class=\"sec1_p_style\">\r\n");
      out.write("                                    세상에 혼자만 남겨진 것 같은 느낌, <br>\r\n");
      out.write("                                    사람의 온기가 필요할 때,\r\n");
      out.write("\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <video class=\"main_video\"\r\n");
      out.write("                                    src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/video/seoul.mp4\" autoplay\r\n");
      out.write("                                    muted loop></video>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mainImg_slide\">\r\n");
      out.write("\r\n");
      out.write("                                <h1 class=\"sec2_h1_style\">우리는 함께 할 때 행복합니다.</h1>\r\n");
      out.write("                                <p class=\"sec2_p_style\">\r\n");
      out.write("                                    외로움을 이기고 새로운 친구와 소중한 인연을 만들기 위해 봉사에 참여합니다.\r\n");
      out.write("                                    <br>나의 따뜻한 마음과 관심을 나누며 함께하는 봉사 활동은 외로움을 극복하는데 큰 도움이 됩니다.\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <video class=\"main_video\"\r\n");
      out.write("                                    src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/video/summer.mp4\" autoplay\r\n");
      out.write("                                    muted loop></video>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mainImg_slide\">\r\n");
      out.write("\r\n");
      out.write("                                <h1 class=\"sec3_h1_style\">우리는 언제나<br> 당신과 함께합니다.</h1>\r\n");
      out.write("                                <p class=\"sec3_p_style\">Hunny는 다양한 기부, 봉사 프로그램이 준비되어 있습니다. <br>\r\n");
      out.write("                                    우리는 언제나 가까운 곳에서 여러분을 기다립니다.</p>\r\n");
      out.write("                                <video class=\"main_video\"\r\n");
      out.write("                                    src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/video/hug.mp4\" autoplay\r\n");
      out.write("                                    muted loop></video>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- \r\n");
      out.write("                    <div class=\"swiper_pagination\">\r\n");
      out.write("                        <div class=\"step active-step\"></div>\r\n");
      out.write("                        <div class=\"step\"></div>\r\n");
      out.write("                        <div class=\"step\"></div>\r\n");
      out.write("                    </div> -->\r\n");
      out.write("\r\n");
      out.write("                        <!-- <div class=\"vol_next_prev_btn\">\r\n");
      out.write("                        <button class=\"vol_swiper_button_prev\">prev</button>\r\n");
      out.write("                        <button class=\"vol_swiper_button_next\">next</button>\r\n");
      out.write("                    </div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <section class=\"contentCount\">\r\n");
      out.write("                    <div class=\"inner title_style\">\r\n");
      out.write("                        <h3 class=\"sub_title\">아름다운 사회를 위해\r\n");
      out.write("                            <br> Hunny가 함께 합니다.\r\n");
      out.write("                        </h3>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"count_box1\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main_img/bunny_01.png\">\r\n");
      out.write("                            <div class=\"count_box1_container\">\r\n");
      out.write("                                <h3>이웃을 향한 아름다운 도움의 손길을<br> 실천하는 Hunny :)</h3>\r\n");
      out.write("                                <p>봉사 1회에 행복지수 10%가 상승하는 사실 알고 계셨나요?<br>Hunny와 함께 나와 우리 이웃의 행복지수를 높여보아요!</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"count_box2\">\r\n");
      out.write("                            <div class=\"vol_count_person\">\r\n");
      out.write("                                <h3><span id=\"volCount\"></span>명</h3>\r\n");
      out.write("                                <p>2023년 Hunny를 통해 이웃들을 위한<br>봉사활동에 참여한 봉사자들 입니다.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"vol_count_money\">\r\n");
      out.write("                                <h3><span id=\"volMoney\"></span>원</h3>\r\n");
      out.write("                                <p>2023년 Hunny에 진행된 기부 활동에<br>모여진 기부금액 입니다.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("                <!-- ***************** 봉사 section ***************** -->\r\n");
      out.write("                <section class=\"volContainer\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"main_sub_title\">\r\n");
      out.write("                        <p>Volunteer</p>\r\n");
      out.write("                        <h3 class=\"sub_title\">이웃을 향한 아름다운 도움의 손길</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"vol_box_container\">\r\n");
      out.write("\r\n");
      out.write("                        <ul class=\"allSlides slidesStyle\">\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"vol_next_prev_btn\">\r\n");
      out.write("                        <span class=\"vol_prev\">prev</span>\r\n");
      out.write("                        <span class=\"vol_next\">next</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("                <!-- ***************** 기부 section ***************** -->\r\n");
      out.write("                <section class=\"donationContainer\">\r\n");
      out.write("                    <div class=\"main_sub_title title_style\">\r\n");
      out.write("                        <p>Donation</p>\r\n");
      out.write("                        <h3 class=\"sub_title\">당신의 관심 한번이 많은 사람을 구합니다.</h3>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"do_blur_box1\"></div>\r\n");
      out.write("                    <div class=\"do_blur_box2\"></div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"do_bigContainer\">\r\n");
      out.write("                        <div class=\"best_img\">\r\n");
      out.write("                            <span>Best</span>\r\n");
      out.write("                            <div class=\"beeImg\"><img\r\n");
      out.write("                                    src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main_img/img_bee.png\"\r\n");
      out.write("                                    alt=\"\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"swiper-container do_box_container\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <ul class=\"swiper-wrapper doAllSlides\">\r\n");
      out.write("                                ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"do_next_prev_btn\">\r\n");
      out.write("                        <span class=\"swiper-button-prev do_prev\">prev</span>\r\n");
      out.write("                        <span class=\"swiper-button-next do_next\">next</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- 리뷰 -->\r\n");
      out.write("                <section class=\"userReview\">\r\n");
      out.write("                    <div class=\"main_sub_title\">\r\n");
      out.write("                        <p>Review</p>\r\n");
      out.write("                        <h3 class=\"sub_title\">참여자 후기</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"re_box_container\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"re_box\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"re_char\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main_img/re_img.png\"\r\n");
      out.write("                                    alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"tag_box\">\r\n");
      out.write("                                <div><img class=\"imgback\"\r\n");
      out.write("                                        src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main_img/tag_box.png\">\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"tag_box_context\">\r\n");
      out.write("                                <div><img\r\n");
      out.write("                                        src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main_img/star_icon.png\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <span>5.0</span>\r\n");
      out.write("                                <span>매우 만족해요!</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"re_content_container\">\r\n");
      out.write("                                <span>완전 추천합니다!</span>\r\n");
      out.write("                                <span class=\"re_content\">\r\n");
      out.write("\r\n");
      out.write("                                    갈 때 마다 어르신들이 너무 반겨 주셔서 제가 힐링받고\r\n");
      out.write("                                    오는 곳입니다. 정말 어르신들 너무 좋으시고 추천합니다!\r\n");
      out.write("\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <span class=\"re_user_name\">유정</span>\r\n");
      out.write("                                    <span>2023. 04. 01 방문 · 재방문 2회</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"re_active_info\">\r\n");
      out.write("                                <span>활동</span>\r\n");
      out.write("                                <span>요양원 입소 어르신 나들이 활동 이동 보조 및 말벗 지원</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"re_box\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"re_char\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main_img/re_img.png\"\r\n");
      out.write("                                    alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"tag_box\">\r\n");
      out.write("                                <div><img class=\"imgback\"\r\n");
      out.write("                                        src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main_img/tag_box.png\">\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"tag_box_context\">\r\n");
      out.write("                                <div><img\r\n");
      out.write("                                        src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main_img/star_icon.png\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <span>5.0</span>\r\n");
      out.write("                                <span>매우 만족해요!</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"re_content_container\">\r\n");
      out.write("                                <span>완전 추천합니다!</span>\r\n");
      out.write("                                <span class=\"re_content\">\r\n");
      out.write("\r\n");
      out.write("                                    갈 때 마다 어르신들이 너무 반겨 주셔서 제가 힐링받고\r\n");
      out.write("                                    오는 곳입니다. 정말 어르신들 너무 좋으시고 추천합니다!\r\n");
      out.write("\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <span class=\"re_user_name\">유정</span>\r\n");
      out.write("                                    <span>2023. 04. 01 방문 · 재방문 2회</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"re_active_info\">\r\n");
      out.write("                                <span>활동</span>\r\n");
      out.write("                                <span>요양원 입소 어르신 나들이 활동 이동 보조 및 말벗 지원</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"re_box\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"re_char\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main_img/re_img.png\"\r\n");
      out.write("                                    alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"tag_box\">\r\n");
      out.write("                                <div><img class=\"imgback\"\r\n");
      out.write("                                        src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main_img/tag_box.png\">\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"tag_box_context\">\r\n");
      out.write("                                <div><img\r\n");
      out.write("                                        src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main_img/star_icon.png\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <span>5.0</span>\r\n");
      out.write("                                <span>매우 만족해요!</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"re_content_container\">\r\n");
      out.write("                                <span>완전 추천합니다!</span>\r\n");
      out.write("                                <span class=\"re_content\">\r\n");
      out.write("\r\n");
      out.write("                                    갈 때 마다 어르신들이 너무 반겨 주셔서 제가 힐링받고\r\n");
      out.write("                                    오는 곳입니다. 정말 어르신들 너무 좋으시고 추천합니다!\r\n");
      out.write("\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <span class=\"re_user_name\">유정</span>\r\n");
      out.write("                                    <span>2023. 04. 01 방문 · 재방문 2회</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"re_active_info\">\r\n");
      out.write("                                <span>활동</span>\r\n");
      out.write("                                <span>요양원 입소 어르신 나들이 활동 이동 보조 및 말벗 지원</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- 푸터 영역 -->\r\n");
      out.write("            <footer>\r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/main/footer.jsp", out, false);
      out.write("\r\n");
      out.write("            </footer>\r\n");
      out.write("\r\n");
      out.write("            <script>\r\n");
      out.write("                (function () { var w = window; if (w.ChannelIO) { return w.console.error(\"ChannelIO script included twice.\"); } var ch = function () { ch.c(arguments); }; ch.q = []; ch.c = function (args) { ch.q.push(args); }; w.ChannelIO = ch; function l() { if (w.ChannelIOInitialized) { return; } w.ChannelIOInitialized = true; var s = document.createElement(\"script\"); s.type = \"text/javascript\"; s.async = true; s.src = \"https://cdn.channel.io/plugin/ch-plugin-web.js\"; var x = document.getElementsByTagName(\"script\")[0]; if (x.parentNode) { x.parentNode.insertBefore(s, x); } } if (document.readyState === \"complete\") { l(); } else { w.addEventListener(\"DOMContentLoaded\", l); w.addEventListener(\"load\", l); } })();\r\n");
      out.write("\r\n");
      out.write("                ChannelIO('boot', {\r\n");
      out.write("                    \"pluginKey\": \"759276e8-069a-4d4a-b4f9-73deebd841e5\"\r\n");
      out.write("                });\r\n");
      out.write("            </script>\r\n");
      out.write("\r\n");
      out.write("            <script>\r\n");
      out.write("                function getVolMoney() {\r\n");
      out.write("                    var xhr2 = new XMLHttpRequest();\r\n");
      out.write("                    xhr2.onreadystatechange = function () {\r\n");
      out.write("                        if (xhr2.readyState === 4 && xhr2.status === 200) {\r\n");
      out.write("                            var volMoney = xhr2.responseText;\r\n");
      out.write("                            document.getElementById(\"volMoney\").textContent = volMoney;\r\n");
      out.write("                        }\r\n");
      out.write("                    };\r\n");
      out.write("                    xhr2.open(\"GET\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/volMoney\", true);\r\n");
      out.write("                    xhr2.send();\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                getVolMoney();\r\n");
      out.write("            </script>\r\n");
      out.write("            <script>\r\n");
      out.write("                function getVolCount() {\r\n");
      out.write("                    var xhr = new XMLHttpRequest();\r\n");
      out.write("                    xhr.onreadystatechange = function () {\r\n");
      out.write("                        if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("                            var volCount = JSON.parse(xhr.responseText);\r\n");
      out.write("                            document.getElementById(\"volCount\").textContent = volCount;\r\n");
      out.write("                        }\r\n");
      out.write("                    };\r\n");
      out.write("                    xhr.open(\"GET\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/volCount\", true);\r\n");
      out.write("                    xhr.send();\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                getVolCount();\r\n");
      out.write("            </script>\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/css/swiper.min.css\">\r\n");
      out.write("            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/js/swiper.min.js\"></script>\r\n");
      out.write("            <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        </body>\r\n");
      out.write("        </html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/main/main.jsp(164,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("volunteer");
      // /WEB-INF/views/main/main.jsp(164,28) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main/main.jsp(164,28) '${mVolunteerList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${mVolunteerList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/main/main.jsp(164,28) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      // /WEB-INF/views/main/main.jsp(164,28) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(0);
      // /WEB-INF/views/main/main.jsp(164,28) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(5);
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                ");
            if (_jspx_meth_c_005fset_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("                                <li class=\"vol_box_style vol_box\" onclick=\"location.href='/volunteer/detail/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${volunteerDetail.volunteerNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("';\">\r\n");
            out.write("                                    <div class=\"vol_day\"><span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${volunteerDetail.DDay}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>D-day</div>\r\n");
            out.write("                                    <div><img\r\n");
            out.write("                                            src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${volunteerDetail.volunteerAttachment}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                                    </div>\r\n");
            out.write("\r\n");
            out.write("                                    <div class=\"vol_content_part\">\r\n");
            out.write("                                        <div class=\"vol_content_per_container\">\r\n");
            out.write("                                            <div class=\"progressBar\">\r\n");
            out.write("                                                <div class=\"progressBarValue\"\r\n");
            out.write("                                                    style=\"width: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${volunteerDetail.percent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("%\"></div>\r\n");
            out.write("                                            </div>\r\n");
            out.write("\r\n");
            out.write("                                            <!-- <span class=\"vol_con_bar\" style=\"width: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${volunteerDetail.percent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("%\"> -->\r\n");
            out.write("                                            <!-- <span class=\"vol_con_bar_per\"></span> -->\r\n");
            out.write("                                            <span\r\n");
            out.write("                                                class=\"tooltip\"><span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${volunteerDetail.volunteerCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${volunteerDetail.targetPeople}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                                            <!-- </span> -->\r\n");
            out.write("                                        </div>\r\n");
            out.write("\r\n");
            out.write("                                        <div class=\"vol_content\">\r\n");
            out.write("                                            <h3>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${volunteer.volunteerTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h3>\r\n");
            out.write("                                            <div>\r\n");
            out.write("                                                <span>모집</span><span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${volunteer.startRecruitDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('~');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${volunteer.endRecruitDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                                            </div>\r\n");
            out.write("                                        </div>\r\n");
            out.write("                                        <div class=\"vol_tag\">\r\n");
            out.write("                                            <div>\r\n");
            out.write("\r\n");
            out.write("                                                <span class=\"vol_tag_child\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${volunteer.parentCategoryName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("\r\n");
            out.write("                                            </div>\r\n");
            out.write("                                           <!--  <div class=\"vol_like\">\r\n");
            out.write("                                                <i class=\"xi-heart-o\"></i>\r\n");
            out.write("                                                <p>102</p>\r\n");
            out.write("                                            </div> -->\r\n");
            out.write("                                        </div>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                </li>\r\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/main/main.jsp(165,32) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("volunteerDetail");
      // /WEB-INF/views/main/main.jsp(165,32) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main/main.jsp(165,32) '${volunteerDetails[status.index]}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${volunteerDetails[status.index]}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/main/main.jsp(241,32) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("donation");
      // /WEB-INF/views/main/main.jsp(241,32) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main/main.jsp(241,32) '${mDonationList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${mDonationList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/main/main.jsp(241,32) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVarStatus("status");
      // /WEB-INF/views/main/main.jsp(241,32) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(0);
      // /WEB-INF/views/main/main.jsp(241,32) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(5);
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                    ");
            if (_jspx_meth_c_005fset_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("                                <li class=\"swiper-slide do_box\" onclick=\"location.href='/donation/detail/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${donationDetail.donationNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("';\">\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("                                    <div class=\"do_right\">\r\n");
            out.write("                                       \r\n");
            out.write("                                        <div class=\"doTitle\">\r\n");
            out.write("                                            <h3>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${donation.donationTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h3>\r\n");
            out.write("                                            <div> 모집 <span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${donation.startRecruitDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write('~');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${donation.endRecruitDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span> </div>\r\n");
            out.write("                                        </div>\r\n");
            out.write("\r\n");
            out.write("                                        <div class=\"vol_content_per_container do_content_per \">\r\n");
            out.write("                                            <div class=\"progressBar do_con_bar\">\r\n");
            out.write("                                                <div class=\"progressBarValue do_con_bar_per \"\r\n");
            out.write("                                                    style=\"width: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${donationDetail.percent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("%\"></div>\r\n");
            out.write("                                            </div>\r\n");
            out.write("\r\n");
            out.write("                                         \r\n");
            out.write("                                             <span class=\"progressPercentage doTooltip\">달성률 ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${donationDetail.percent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("% </span>\r\n");
            out.write("                                        </div>\r\n");
            out.write("                                        \r\n");
            out.write("                                         <div class=\"do_tag_container\">\r\n");
            out.write("                                            <div class=\"do_tag\">\r\n");
            out.write("                                                <span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${donation.parentCategoryName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                                            </div>\r\n");
            out.write("                                            <div class=\"do_like\">\r\n");
            out.write("                                                <div>❤️</div>\r\n");
            out.write("                                                <span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${donationDetail.favCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("명이 추천해요!</span>\r\n");
            out.write("                                            </div>\r\n");
            out.write("                                        </div>\r\n");
            out.write("\r\n");
            out.write("                                       ");
            out.write("\r\n");
            out.write("                                    </div>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("                                    <div class=\"do_left\">\r\n");
            out.write("                                        <div class=\"divImg\"><img\r\n");
            out.write("                                                src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${donationDetail.donationAttachment}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("                                                alt=\"\"></div>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                    \r\n");
            out.write("                                </li>\r\n");
            out.write("                                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/main/main.jsp(242,36) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("donationDetail");
      // /WEB-INF/views/main/main.jsp(242,36) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main/main.jsp(242,36) '${donationDetails[status.index]}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${donationDetails[status.index]}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }
}
